### PR TITLE
Add max frame rate calculation to ARIS Integration SDK.

### PR DESCRIPTION
**Pull request by fvasquez**
Also moved reordering and depth unit tests from diverheld build to ARIS Integration SDK.
Addresses SoundMetrics/aris-onboard#40.
Note that unit tests need to be run in Visual Studio with x64 selected as Default Processor Architecture under Test Settings menu.

### CODE REVIEW

**Comment by fvasquez** [comment]
Unit tests have been split into three folders.  FrameRate/UnitTests must be run in an x64 process.

**Comment by fvasquez** [comment]
> Why must these be run as 64-bit processes? Do they not build as 32-bit?

I'm sorry.  I meant Reordering/UnitTests need to be run in an x64 process.
The reason is that the relative paths to the input and expected data files are one level higher for x64.

```
aris-integration-sdk\common\code\Reordering\UnitTests\data
aris-integration-sdk\common\code\Reordering\UnitTests\Debug
aris-integration-sdk\common\code\Reordering\UnitTests\x64\Debug
```
So the paths to .dat files in the unit tests are prefixed with ../../ instead of ../.
The tests build in 32-bit but fail at execution time because the .dat files are not found.
I chose to enable x64 over 32-bit because I figured more people would be consuming the code that way.
There's probably a good way to solve this problem (resources files maybe?) but I haven't looked into it yet.
I didn't want to switch to absolute paths or introduce conditional (x86 vs x64) logic.

**Comment by curtnichols** [comment]
The only people known to use this code run 32-bit processes. More than that, we should run both in CI. Feel free to check pointer size to adjust the path to the data files.

**Comment by curtnichols** [comment]
Ugh, 10 commits due to the merge. Please start squashing your merge.

**Pull request merged**
